swagger: '2.0'
info:
    title: OnTheRoad API documentation
    description: Contains all available API endpoints in this codebase
    version: 1.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3000
basePath: /api/v1
schemes:
    - http
paths:
    /getUsers:
        get:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: Read users
            description: Get all users
            produces:
                - application/json
            responses:
                '200':
                    description: Retrieve all users
                    schema:
                        $ref: '#/definitions/getUser'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /newUser:
        post:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: Add users
            description: Add new users
            parameters:
                - in: body
                  name: body
                  description: Parameter to add new user
                  required: true
                  schema:
                      $ref: '#/definitions/newUser'
            produces:
                - application/json
            responses:
                '200':
                    description: Retrieve User success
                    schema:
                        $ref: '#/definitions/getUser'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    getUser:
        type: object
        properties:
            email:
                type: string
                description: user email
            firstName:
                type: string
                description: user first name
            lastName:
                type: string
                description: user last name
    newUser:
        type: object
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
            firstName:
                type: string
                description: user first name
            lastName:
                type: string
                description: user last name
    ID_Response:
        type: object
        properties:
            token:
                type: string
