swagger: '2.0'
info:
    title: OnTheRoad API documentation
    description: Contains all available API endpoints in this codebase
    version: 1.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3000
basePath: /api/v1
schemes:
    - http
paths:
    /getAPI:
        get:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: Read api
            description: API id
            produces:
                - application/json
            responses:
                '200':
                    description: ID retrieve
                    schema:
                        $ref: '#/definitions/ID_Response'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    ID_Response:
        type: object
        properties:
            token:
                type: string
